services:
  # Service Symfony - Projet Emyst
  symfony:
    build:
      context: .
      dockerfile: Dockerfile.symfony
    container_name: emyst_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./var:/var/www/html/var
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER:-emyst_user}:${MYSQL_PASSWORD:-Emyst_S3cur3_P@ss_2024!}@mysql:3306/${MYSQL_DATABASE:-emyst_db}?serverVersion=8.0
    networks:
      - emyst_network

  # Service MySQL - Projet Emyst
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: emyst_mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Si vous avez des scripts d'initialisation SQL, dÃ©commentez :
      # - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-Emyst_R00t_P@ssw0rd_2024!}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-emyst_db}
      - MYSQL_USER=${MYSQL_USER:-emyst_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-Emyst_S3cur3_P@ss_2024!}
    networks:
      - emyst_network

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  mysql_data:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
    name: emyst_mysql_data

networks:
  emyst_network:
    driver: bridge
